#!/bin/bash
# Pack every basketball take of EgoExo4D participant 363, plus each take's fisheye
# calibration. Generated by tools/gen_tar_expert.py; see the other
# tar_expert*.sh for the conventions.
#
# WHO THIS IS. Early Expert, female, unc. unc_basketball_03-09-23_02, shared with 364 and 365.
#
# 7 takes, 9.8 minutes. Take indices: 1, 2, 3, 74, 76, 78, 80.
# Capture(s): unc_basketball_03-09-23_01, unc_basketball_03-09-23_02.
#
# CAMERAS, every take: cam01,cam02,cam03,cam04.
# The camera set is a property of the CAPTURE, not the university, and
# scripts/recon_common.sh reads each take's list off disk -- but check it
# matches before masking, and never copy an ALL_CAMS value between captures.
#
# The pipeline camera is resolved from the take's own best_exo now, so no
# manifest row is needed for it. Confirm against the stage-1 mask overlay
# before committing a capture to a view.
#
# WHAT EACH TAKE CONTRIBUTES:
#   frame_aligned_videos/cam0N.mp4         the 4K exo views
#   frame_aligned_videos/downscaled/448    the pipeline-resolution copies (dir)
#   trajectory/gopro_calibs.csv            per-take fisheye calibration
#
# Verify availability on the mirror BEFORE running this:
#
#   python3 -c "import json,os; R='/vision/group/egoexo4d/takes'; T=json.load(open('/vision/group/egoexo4d/takes.json')); [print('%-34s cams=%d 448=%d calib=%s' % (t['take_name'], sum(os.path.isfile('%s/%s/frame_aligned_videos/%s.mp4'%(R,t['take_name'],c)) for c in sorted(k for k in (t.get('frame_aligned_videos') or {}) if k.startswith('cam'))), len(os.listdir('%s/%s/frame_aligned_videos/downscaled/448'%(R,t['take_name']))) if os.path.isdir('%s/%s/frame_aligned_videos/downscaled/448'%(R,t['take_name'])) else 0, os.path.isfile('%s/%s/trajectory/gopro_calibs.csv'%(R,t['take_name'])))) for t in sorted(T,key=lambda x:x['take_idx']) if t.get('participant_uid')==363]"
#
#   bash scripts/tar_expert363.sh                    # -> <repo>/expert363_takes.tar
#   OUT=/scratch/expert363.tar bash scripts/tar_expert363.sh
#
# The archive is roughly 3.9 GB. Run it detached -- the -v output floods a
# terminal and a Ctrl-C leaves a truncated archive with no resume:
#   nohup bash scripts/tar_expert363.sh > tar363.log 2>&1 &

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

TAKES_ROOT="${TAKES_ROOT:-/vision/group/egoexo4d/takes}"
OUT="${OUT:-$REPO/expert363_takes.tar}"

[ -d "$TAKES_ROOT" ] || { echo "ERROR: no takes root at $TAKES_ROOT" >&2; exit 1; }
mkdir -p "$(dirname "$OUT")"

# Checked before a byte is written. Filling a quota mid-tar leaves a truncated
# archive that looks finished, which is a worse failure than refusing to start.
NEED_KB=6188578
AVAIL_KB=$(df -Pk "$(dirname "$OUT")" | awk 'NR==2 {print $4}')
if [ "$AVAIL_KB" -lt "$NEED_KB" ]; then
    echo "ERROR: need ~$((NEED_KB / 1024 / 1024)) GB at $(dirname "$OUT"), have $((AVAIL_KB / 1024 / 1024)) GB" >&2
    echo "       set OUT to somewhere with room" >&2
    exit 1
fi

cd "$TAKES_ROOT"

# -c create, -h follow symlinks, -v so the log shows every file, -f the
# archive. No -z: the payload is already-encoded H.264.
tar -chvf "$OUT" \
    unc_basketball_03-09-23_02_1/frame_aligned_videos/cam01.mp4 \
    unc_basketball_03-09-23_02_1/frame_aligned_videos/cam02.mp4 \
    unc_basketball_03-09-23_02_1/frame_aligned_videos/cam03.mp4 \
    unc_basketball_03-09-23_02_1/frame_aligned_videos/cam04.mp4 \
    unc_basketball_03-09-23_02_1/frame_aligned_videos/downscaled/448 \
    unc_basketball_03-09-23_02_1/trajectory/gopro_calibs.csv \
    unc_basketball_03-09-23_02_2/frame_aligned_videos/cam01.mp4 \
    unc_basketball_03-09-23_02_2/frame_aligned_videos/cam02.mp4 \
    unc_basketball_03-09-23_02_2/frame_aligned_videos/cam03.mp4 \
    unc_basketball_03-09-23_02_2/frame_aligned_videos/cam04.mp4 \
    unc_basketball_03-09-23_02_2/frame_aligned_videos/downscaled/448 \
    unc_basketball_03-09-23_02_2/trajectory/gopro_calibs.csv \
    unc_basketball_03-09-23_02_3/frame_aligned_videos/cam01.mp4 \
    unc_basketball_03-09-23_02_3/frame_aligned_videos/cam02.mp4 \
    unc_basketball_03-09-23_02_3/frame_aligned_videos/cam03.mp4 \
    unc_basketball_03-09-23_02_3/frame_aligned_videos/cam04.mp4 \
    unc_basketball_03-09-23_02_3/frame_aligned_videos/downscaled/448 \
    unc_basketball_03-09-23_02_3/trajectory/gopro_calibs.csv \
    unc_basketball_03-09-23_01_74/frame_aligned_videos/cam01.mp4 \
    unc_basketball_03-09-23_01_74/frame_aligned_videos/cam02.mp4 \
    unc_basketball_03-09-23_01_74/frame_aligned_videos/cam03.mp4 \
    unc_basketball_03-09-23_01_74/frame_aligned_videos/cam04.mp4 \
    unc_basketball_03-09-23_01_74/frame_aligned_videos/downscaled/448 \
    unc_basketball_03-09-23_01_74/trajectory/gopro_calibs.csv \
    unc_basketball_03-09-23_01_76/frame_aligned_videos/cam01.mp4 \
    unc_basketball_03-09-23_01_76/frame_aligned_videos/cam02.mp4 \
    unc_basketball_03-09-23_01_76/frame_aligned_videos/cam03.mp4 \
    unc_basketball_03-09-23_01_76/frame_aligned_videos/cam04.mp4 \
    unc_basketball_03-09-23_01_76/frame_aligned_videos/downscaled/448 \
    unc_basketball_03-09-23_01_76/trajectory/gopro_calibs.csv \
    unc_basketball_03-09-23_01_78/frame_aligned_videos/cam01.mp4 \
    unc_basketball_03-09-23_01_78/frame_aligned_videos/cam02.mp4 \
    unc_basketball_03-09-23_01_78/frame_aligned_videos/cam03.mp4 \
    unc_basketball_03-09-23_01_78/frame_aligned_videos/cam04.mp4 \
    unc_basketball_03-09-23_01_78/frame_aligned_videos/downscaled/448 \
    unc_basketball_03-09-23_01_78/trajectory/gopro_calibs.csv \
    unc_basketball_03-09-23_01_80/frame_aligned_videos/cam01.mp4 \
    unc_basketball_03-09-23_01_80/frame_aligned_videos/cam02.mp4 \
    unc_basketball_03-09-23_01_80/frame_aligned_videos/cam03.mp4 \
    unc_basketball_03-09-23_01_80/frame_aligned_videos/cam04.mp4 \
    unc_basketball_03-09-23_01_80/frame_aligned_videos/downscaled/448 \
    unc_basketball_03-09-23_01_80/trajectory/gopro_calibs.csv

echo ""
echo "wrote $OUT  ($(du -h "$OUT" | cut -f1))"
echo "entries: $(tar -tf "$OUT" | wc -l)"
echo ""
echo "expected: 7 takes x (their cameras + the 448 dir record + its files + calib)"
echo ""
echo "extract on the other side with:"
echo "  tar -xf $(basename "$OUT") -C /their/egoexo4d/takes"
