#!/bin/bash
# Pack every salsa take of EgoExo4D participant 248, plus each take's fisheye
# calibration. Generated by tools/gen_tar_expert.py; see the other
# tar_expert*.sh for the conventions.
#
# WHO THIS IS. Late Expert x10; female, uniandes. 10 salsa takes in uniandes_dance_022.
#
# 10 takes, 10.4 minutes. Take indices: 15, 16, 17, 18, 20, 22, 23, 25, 26, 27.
# Capture(s): uniandes_dance_022.
#
# CAMERAS, every take: cam01,cam02,cam03,cam04,cam05.
# The camera set is a property of the CAPTURE, not the university, and
# scripts/recon_common.sh reads each take's list off disk -- but check it
# matches before masking, and never copy an ALL_CAMS value between captures.
#
# The pipeline camera is resolved from the take's own best_exo now, so no
# manifest row is needed for it. Confirm against the stage-1 mask overlay
# before committing a capture to a view.
#
# WHAT EACH TAKE CONTRIBUTES:
#   frame_aligned_videos/cam0N.mp4         the 4K exo views (gp0N.mp4 at upenn)
#   frame_aligned_videos/downscaled/448    the pipeline-resolution copies (dir)
#   trajectory/gopro_calibs.csv            per-take fisheye calibration
#
# Verify availability on the mirror BEFORE running this:
#
#   python3 -c "import json,os; R='/vision/group/egoexo4d/takes'; T=json.load(open('/vision/group/egoexo4d/takes.json')); [print('%-34s cams=%d 448=%d calib=%s' % (t['take_name'], sum(os.path.isfile('%s/%s/frame_aligned_videos/%s.mp4'%(R,t['take_name'],c)) for c in sorted(k for k in (t.get('frame_aligned_videos') or {}) if k.startswith(('cam','gp')))), len(os.listdir('%s/%s/frame_aligned_videos/downscaled/448'%(R,t['take_name']))) if os.path.isdir('%s/%s/frame_aligned_videos/downscaled/448'%(R,t['take_name'])) else 0, os.path.isfile('%s/%s/trajectory/gopro_calibs.csv'%(R,t['take_name'])))) for t in sorted(T,key=lambda x:x['take_idx']) if t.get('participant_uid')==248]"
#
#   bash scripts/tar_expert248.sh                    # -> <repo>/expert248_takes.tar
#   OUT=/scratch/expert248.tar bash scripts/tar_expert248.sh
#
# The archive is roughly 5.1 GB. Run it detached -- the -v output floods a
# terminal and a Ctrl-C leaves a truncated archive with no resume:
#   nohup bash scripts/tar_expert248.sh > tar248.log 2>&1 &

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

TAKES_ROOT="${TAKES_ROOT:-/vision/group/egoexo4d/takes}"
OUT="${OUT:-$REPO/expert248_takes.tar}"

[ -d "$TAKES_ROOT" ] || { echo "ERROR: no takes root at $TAKES_ROOT" >&2; exit 1; }
mkdir -p "$(dirname "$OUT")"

# Checked before a byte is written. Filling a quota mid-tar leaves a truncated
# archive that looks finished, which is a worse failure than refusing to start.
NEED_KB=7731069
AVAIL_KB=$(df -Pk "$(dirname "$OUT")" | awk 'NR==2 {print $4}')
if [ "$AVAIL_KB" -lt "$NEED_KB" ]; then
    echo "ERROR: need ~$((NEED_KB / 1024 / 1024)) GB at $(dirname "$OUT"), have $((AVAIL_KB / 1024 / 1024)) GB" >&2
    echo "       set OUT to somewhere with room" >&2
    exit 1
fi

cd "$TAKES_ROOT"

# -c create, -h follow symlinks, -v so the log shows every file, -f the
# archive. No -z: the payload is already-encoded H.264.
tar -chvf "$OUT" \
    uniandes_dance_022_15/frame_aligned_videos/cam01.mp4 \
    uniandes_dance_022_15/frame_aligned_videos/cam02.mp4 \
    uniandes_dance_022_15/frame_aligned_videos/cam03.mp4 \
    uniandes_dance_022_15/frame_aligned_videos/cam04.mp4 \
    uniandes_dance_022_15/frame_aligned_videos/cam05.mp4 \
    uniandes_dance_022_15/frame_aligned_videos/downscaled/448 \
    uniandes_dance_022_15/trajectory/gopro_calibs.csv \
    uniandes_dance_022_16/frame_aligned_videos/cam01.mp4 \
    uniandes_dance_022_16/frame_aligned_videos/cam02.mp4 \
    uniandes_dance_022_16/frame_aligned_videos/cam03.mp4 \
    uniandes_dance_022_16/frame_aligned_videos/cam04.mp4 \
    uniandes_dance_022_16/frame_aligned_videos/cam05.mp4 \
    uniandes_dance_022_16/frame_aligned_videos/downscaled/448 \
    uniandes_dance_022_16/trajectory/gopro_calibs.csv \
    uniandes_dance_022_17/frame_aligned_videos/cam01.mp4 \
    uniandes_dance_022_17/frame_aligned_videos/cam02.mp4 \
    uniandes_dance_022_17/frame_aligned_videos/cam03.mp4 \
    uniandes_dance_022_17/frame_aligned_videos/cam04.mp4 \
    uniandes_dance_022_17/frame_aligned_videos/cam05.mp4 \
    uniandes_dance_022_17/frame_aligned_videos/downscaled/448 \
    uniandes_dance_022_17/trajectory/gopro_calibs.csv \
    uniandes_dance_022_18/frame_aligned_videos/cam01.mp4 \
    uniandes_dance_022_18/frame_aligned_videos/cam02.mp4 \
    uniandes_dance_022_18/frame_aligned_videos/cam03.mp4 \
    uniandes_dance_022_18/frame_aligned_videos/cam04.mp4 \
    uniandes_dance_022_18/frame_aligned_videos/cam05.mp4 \
    uniandes_dance_022_18/frame_aligned_videos/downscaled/448 \
    uniandes_dance_022_18/trajectory/gopro_calibs.csv \
    uniandes_dance_022_20/frame_aligned_videos/cam01.mp4 \
    uniandes_dance_022_20/frame_aligned_videos/cam02.mp4 \
    uniandes_dance_022_20/frame_aligned_videos/cam03.mp4 \
    uniandes_dance_022_20/frame_aligned_videos/cam04.mp4 \
    uniandes_dance_022_20/frame_aligned_videos/cam05.mp4 \
    uniandes_dance_022_20/frame_aligned_videos/downscaled/448 \
    uniandes_dance_022_20/trajectory/gopro_calibs.csv \
    uniandes_dance_022_22/frame_aligned_videos/cam01.mp4 \
    uniandes_dance_022_22/frame_aligned_videos/cam02.mp4 \
    uniandes_dance_022_22/frame_aligned_videos/cam03.mp4 \
    uniandes_dance_022_22/frame_aligned_videos/cam04.mp4 \
    uniandes_dance_022_22/frame_aligned_videos/cam05.mp4 \
    uniandes_dance_022_22/frame_aligned_videos/downscaled/448 \
    uniandes_dance_022_22/trajectory/gopro_calibs.csv \
    uniandes_dance_022_23/frame_aligned_videos/cam01.mp4 \
    uniandes_dance_022_23/frame_aligned_videos/cam02.mp4 \
    uniandes_dance_022_23/frame_aligned_videos/cam03.mp4 \
    uniandes_dance_022_23/frame_aligned_videos/cam04.mp4 \
    uniandes_dance_022_23/frame_aligned_videos/cam05.mp4 \
    uniandes_dance_022_23/frame_aligned_videos/downscaled/448 \
    uniandes_dance_022_23/trajectory/gopro_calibs.csv \
    uniandes_dance_022_25/frame_aligned_videos/cam01.mp4 \
    uniandes_dance_022_25/frame_aligned_videos/cam02.mp4 \
    uniandes_dance_022_25/frame_aligned_videos/cam03.mp4 \
    uniandes_dance_022_25/frame_aligned_videos/cam04.mp4 \
    uniandes_dance_022_25/frame_aligned_videos/cam05.mp4 \
    uniandes_dance_022_25/frame_aligned_videos/downscaled/448 \
    uniandes_dance_022_25/trajectory/gopro_calibs.csv \
    uniandes_dance_022_26/frame_aligned_videos/cam01.mp4 \
    uniandes_dance_022_26/frame_aligned_videos/cam02.mp4 \
    uniandes_dance_022_26/frame_aligned_videos/cam03.mp4 \
    uniandes_dance_022_26/frame_aligned_videos/cam04.mp4 \
    uniandes_dance_022_26/frame_aligned_videos/cam05.mp4 \
    uniandes_dance_022_26/frame_aligned_videos/downscaled/448 \
    uniandes_dance_022_26/trajectory/gopro_calibs.csv \
    uniandes_dance_022_27/frame_aligned_videos/cam01.mp4 \
    uniandes_dance_022_27/frame_aligned_videos/cam02.mp4 \
    uniandes_dance_022_27/frame_aligned_videos/cam03.mp4 \
    uniandes_dance_022_27/frame_aligned_videos/cam04.mp4 \
    uniandes_dance_022_27/frame_aligned_videos/cam05.mp4 \
    uniandes_dance_022_27/frame_aligned_videos/downscaled/448 \
    uniandes_dance_022_27/trajectory/gopro_calibs.csv

echo ""
echo "wrote $OUT  ($(du -h "$OUT" | cut -f1))"
echo "entries: $(tar -tf "$OUT" | wc -l)"
echo ""
echo "expected: 10 takes x (their cameras + the 448 dir record + its files + calib)"
echo ""
echo "extract on the other side with:"
echo "  tar -xf $(basename "$OUT") -C /their/egoexo4d/takes"
