#!/bin/bash
# Pack every basketball take of EgoExo4D participant 407, plus each take's fisheye
# calibration. Generated by tools/gen_tar_expert.py; see the other
# tar_expert*.sh for the conventions.
#
# WHO THIS IS. Late Expert, gender not recorded, sfu. 11 takes in sfu_basketball_01. Shares a capture with 408, 409, so that calibration covers several people.
#
# 11 takes, 5.9 minutes. Take indices: 2, 4, 6, 19, 20, 22, 23, 24, 37, 39, 41.
# Capture(s): sfu_basketball_01.
#
# CAMERAS, every take: cam01,cam02,cam03,cam04.
# The camera set is a property of the CAPTURE, not the university, and
# scripts/recon_common.sh reads each take's list off disk -- but check it
# matches before masking, and never copy an ALL_CAMS value between captures.
#
# The pipeline camera is resolved from the take's own best_exo now, so no
# manifest row is needed for it. Confirm against the stage-1 mask overlay
# before committing a capture to a view.
#
# WHAT EACH TAKE CONTRIBUTES:
#   frame_aligned_videos/cam0N.mp4         the 4K exo views
#   frame_aligned_videos/downscaled/448    the pipeline-resolution copies (dir)
#   trajectory/gopro_calibs.csv            per-take fisheye calibration
#
# Verify availability on the mirror BEFORE running this:
#
#   python3 -c "import json,os; R='/vision/group/egoexo4d/takes'; T=json.load(open('/vision/group/egoexo4d/takes.json')); [print('%-34s cams=%d 448=%d calib=%s' % (t['take_name'], sum(os.path.isfile('%s/%s/frame_aligned_videos/%s.mp4'%(R,t['take_name'],c)) for c in sorted(k for k in (t.get('frame_aligned_videos') or {}) if k.startswith('cam'))), len(os.listdir('%s/%s/frame_aligned_videos/downscaled/448'%(R,t['take_name']))) if os.path.isdir('%s/%s/frame_aligned_videos/downscaled/448'%(R,t['take_name'])) else 0, os.path.isfile('%s/%s/trajectory/gopro_calibs.csv'%(R,t['take_name'])))) for t in sorted(T,key=lambda x:x['take_idx']) if t.get('participant_uid')==407]"
#
#   bash scripts/tar_expert407.sh                    # -> <repo>/expert407_takes.tar
#   OUT=/scratch/expert407.tar bash scripts/tar_expert407.sh
#
# The archive is roughly 2.3 GB. Run it detached -- the -v output floods a
# terminal and a Ctrl-C leaves a truncated archive with no resume:
#   nohup bash scripts/tar_expert407.sh > tar407.log 2>&1 &

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

TAKES_ROOT="${TAKES_ROOT:-/vision/group/egoexo4d/takes}"
OUT="${OUT:-$REPO/expert407_takes.tar}"

[ -d "$TAKES_ROOT" ] || { echo "ERROR: no takes root at $TAKES_ROOT" >&2; exit 1; }
mkdir -p "$(dirname "$OUT")"

# Checked before a byte is written. Filling a quota mid-tar leaves a truncated
# archive that looks finished, which is a worse failure than refusing to start.
NEED_KB=4124859
AVAIL_KB=$(df -Pk "$(dirname "$OUT")" | awk 'NR==2 {print $4}')
if [ "$AVAIL_KB" -lt "$NEED_KB" ]; then
    echo "ERROR: need ~$((NEED_KB / 1024 / 1024)) GB at $(dirname "$OUT"), have $((AVAIL_KB / 1024 / 1024)) GB" >&2
    echo "       set OUT to somewhere with room" >&2
    exit 1
fi

cd "$TAKES_ROOT"

# -c create, -h follow symlinks, -v so the log shows every file, -f the
# archive. No -z: the payload is already-encoded H.264.
tar -chvf "$OUT" \
    sfu_basketball_01_2/frame_aligned_videos/cam01.mp4 \
    sfu_basketball_01_2/frame_aligned_videos/cam02.mp4 \
    sfu_basketball_01_2/frame_aligned_videos/cam03.mp4 \
    sfu_basketball_01_2/frame_aligned_videos/cam04.mp4 \
    sfu_basketball_01_2/frame_aligned_videos/downscaled/448 \
    sfu_basketball_01_2/trajectory/gopro_calibs.csv \
    sfu_basketball_01_4/frame_aligned_videos/cam01.mp4 \
    sfu_basketball_01_4/frame_aligned_videos/cam02.mp4 \
    sfu_basketball_01_4/frame_aligned_videos/cam03.mp4 \
    sfu_basketball_01_4/frame_aligned_videos/cam04.mp4 \
    sfu_basketball_01_4/frame_aligned_videos/downscaled/448 \
    sfu_basketball_01_4/trajectory/gopro_calibs.csv \
    sfu_basketball_01_6/frame_aligned_videos/cam01.mp4 \
    sfu_basketball_01_6/frame_aligned_videos/cam02.mp4 \
    sfu_basketball_01_6/frame_aligned_videos/cam03.mp4 \
    sfu_basketball_01_6/frame_aligned_videos/cam04.mp4 \
    sfu_basketball_01_6/frame_aligned_videos/downscaled/448 \
    sfu_basketball_01_6/trajectory/gopro_calibs.csv \
    sfu_basketball_01_19/frame_aligned_videos/cam01.mp4 \
    sfu_basketball_01_19/frame_aligned_videos/cam02.mp4 \
    sfu_basketball_01_19/frame_aligned_videos/cam03.mp4 \
    sfu_basketball_01_19/frame_aligned_videos/cam04.mp4 \
    sfu_basketball_01_19/frame_aligned_videos/downscaled/448 \
    sfu_basketball_01_19/trajectory/gopro_calibs.csv \
    sfu_basketball_01_20/frame_aligned_videos/cam01.mp4 \
    sfu_basketball_01_20/frame_aligned_videos/cam02.mp4 \
    sfu_basketball_01_20/frame_aligned_videos/cam03.mp4 \
    sfu_basketball_01_20/frame_aligned_videos/cam04.mp4 \
    sfu_basketball_01_20/frame_aligned_videos/downscaled/448 \
    sfu_basketball_01_20/trajectory/gopro_calibs.csv \
    sfu_basketball_01_22/frame_aligned_videos/cam01.mp4 \
    sfu_basketball_01_22/frame_aligned_videos/cam02.mp4 \
    sfu_basketball_01_22/frame_aligned_videos/cam03.mp4 \
    sfu_basketball_01_22/frame_aligned_videos/cam04.mp4 \
    sfu_basketball_01_22/frame_aligned_videos/downscaled/448 \
    sfu_basketball_01_22/trajectory/gopro_calibs.csv \
    sfu_basketball_01_23/frame_aligned_videos/cam01.mp4 \
    sfu_basketball_01_23/frame_aligned_videos/cam02.mp4 \
    sfu_basketball_01_23/frame_aligned_videos/cam03.mp4 \
    sfu_basketball_01_23/frame_aligned_videos/cam04.mp4 \
    sfu_basketball_01_23/frame_aligned_videos/downscaled/448 \
    sfu_basketball_01_23/trajectory/gopro_calibs.csv \
    sfu_basketball_01_24/frame_aligned_videos/cam01.mp4 \
    sfu_basketball_01_24/frame_aligned_videos/cam02.mp4 \
    sfu_basketball_01_24/frame_aligned_videos/cam03.mp4 \
    sfu_basketball_01_24/frame_aligned_videos/cam04.mp4 \
    sfu_basketball_01_24/frame_aligned_videos/downscaled/448 \
    sfu_basketball_01_24/trajectory/gopro_calibs.csv \
    sfu_basketball_01_37/frame_aligned_videos/cam01.mp4 \
    sfu_basketball_01_37/frame_aligned_videos/cam02.mp4 \
    sfu_basketball_01_37/frame_aligned_videos/cam03.mp4 \
    sfu_basketball_01_37/frame_aligned_videos/cam04.mp4 \
    sfu_basketball_01_37/frame_aligned_videos/downscaled/448 \
    sfu_basketball_01_37/trajectory/gopro_calibs.csv \
    sfu_basketball_01_39/frame_aligned_videos/cam01.mp4 \
    sfu_basketball_01_39/frame_aligned_videos/cam02.mp4 \
    sfu_basketball_01_39/frame_aligned_videos/cam03.mp4 \
    sfu_basketball_01_39/frame_aligned_videos/cam04.mp4 \
    sfu_basketball_01_39/frame_aligned_videos/downscaled/448 \
    sfu_basketball_01_39/trajectory/gopro_calibs.csv \
    sfu_basketball_01_41/frame_aligned_videos/cam01.mp4 \
    sfu_basketball_01_41/frame_aligned_videos/cam02.mp4 \
    sfu_basketball_01_41/frame_aligned_videos/cam03.mp4 \
    sfu_basketball_01_41/frame_aligned_videos/cam04.mp4 \
    sfu_basketball_01_41/frame_aligned_videos/downscaled/448 \
    sfu_basketball_01_41/trajectory/gopro_calibs.csv

echo ""
echo "wrote $OUT  ($(du -h "$OUT" | cut -f1))"
echo "entries: $(tar -tf "$OUT" | wc -l)"
echo ""
echo "expected: 11 takes x (their cameras + the 448 dir record + its files + calib)"
echo ""
echo "extract on the other side with:"
echo "  tar -xf $(basename "$OUT") -C /their/egoexo4d/takes"
