"""Generate a scripts/tar_expert<pid>.sh for one EgoExo4D participant.

The tar scripts name every path literally so what gets packed is auditable by
reading the file. That property is worth keeping and hand-typing is not: a
participant with 18 takes is 108 paths, and the camera set differs per take
(iiith_soccer_002 has no cam02, utokyo soccer has five cameras, upenn cooking
uses gp01-gp06 and is not supported here at all). So the literal list is
generated from takes.json and checked, rather than transcribed.

    python tools/gen_tar_expert.py 380 --task "basketball" \
        --note "Late Expert, one of three in unc_basketball_03-30-23_01."

Writes scripts/tar_expert380.sh. Existing files are left alone unless --force.
"""
import argparse
import json
import os
import sys

sys.path.append(os.getcwd())

# Bytes per second of 4K exo video, measured off unc_basketball_03-31-23_02_9:
# 398 MB of cam01-cam04 over 64.1 s, so ~1.55 MB/s per camera, plus ~0.6 MB/s
# for the whole downscaled/448 directory. Only used to size the free-space
# check, so it is deliberately generous rather than exact.
MB_PER_CAM_SECOND = 1.55
MB_PER_SECOND_448 = 0.6


def load_takes(path):
    """Read takes.json from `path`, or the usual places if it is None."""
    for p in (path, os.environ.get('EGOEXO_TAKES_JSON'),
              os.path.expanduser('~/egoexo4d/takes.json')):
        if p and os.path.isfile(p):
            with open(p) as f:
                return json.load(f)
    raise SystemExit('could not find takes.json; pass --takes_json')


def takes_for(takes, pid, tasks=None, scenario=None):
    """Return this participant's non-dropped takes, sorted by index.

    `tasks` filters by task_name, which is how a cooking participant is
    restricted to the pan dishes rather than their salads. `scenario` filters
    by parent_task_name, and one of the two is effectively required: a
    participant can appear in more than one scenario, and without a filter
    this returns all of it. Participant 833 is a soccer expert who also
    cooked, and an unfiltered call packed ten cooking takes -- salads
    included -- into what was meant to be a soccer subject.
    """
    out = [t for t in takes
           if t.get('participant_uid') == pid and not t.get('is_dropped')
           and (tasks is None or t['task_name'] in tasks)
           and (scenario is None or t.get('parent_task_name') == scenario)]
    return sorted(out, key=lambda t: t['take_idx'])


def cams_of(take):
    """Exo camera names this take actually has, from its frame_aligned_videos."""
    fav = take.get('frame_aligned_videos') or {}
    return sorted(c for c in fav if c.startswith('cam'))


def estimate_gb(takes):
    """Rough archive size in GB, for the script's pre-flight free-space check."""
    mb = sum(t['duration_sec'] * (len(cams_of(t)) * MB_PER_CAM_SECOND + MB_PER_SECOND_448)
             for t in takes)
    return mb / 1024.0


def path_lines(takes):
    """The literal tar arguments: every camera, the 448 dir, the calibration."""
    lines = []
    for t in takes:
        n = t['take_name']
        for c in cams_of(t):
            lines.append(f'    {n}/frame_aligned_videos/{c}.mp4')
        lines.append(f'    {n}/frame_aligned_videos/downscaled/448')
        lines.append(f'    {n}/trajectory/gopro_calibs.csv')
    return lines


def header(pid, takes, note, task, gb):
    """The comment block: who this is, what is packed, and what to watch for."""
    caps = sorted({t['take_name'].rsplit('_', 1)[0] for t in takes})
    camsets = sorted({','.join(cams_of(t)) for t in takes})
    secs = sum(t['duration_sec'] for t in takes)
    idx = ', '.join(str(t['take_idx']) for t in takes)
    cam_line = ('every take: ' + camsets[0]) if len(camsets) == 1 else \
               ('VARIES BY TAKE: ' + ' | '.join(camsets))
    return f'''#!/bin/bash
# Pack every {task} take of EgoExo4D participant {pid}, plus each take's fisheye
# calibration. Generated by tools/gen_tar_expert.py; see the other
# tar_expert*.sh for the conventions.
#
# WHO THIS IS. {note}
#
# {len(takes)} takes, {secs / 60:.1f} minutes. Take indices: {idx}.
# Capture(s): {', '.join(caps)}.
#
# CAMERAS, {cam_line}.
# The camera set is a property of the CAPTURE, not the university, and
# scripts/recon_common.sh reads each take's list off disk -- but check it
# matches before masking, and never copy an ALL_CAMS value between captures.
#
# The pipeline camera is resolved from the take's own best_exo now, so no
# manifest row is needed for it. Confirm against the stage-1 mask overlay
# before committing a capture to a view.
#
# WHAT EACH TAKE CONTRIBUTES:
#   frame_aligned_videos/cam0N.mp4         the 4K exo views
#   frame_aligned_videos/downscaled/448    the pipeline-resolution copies (dir)
#   trajectory/gopro_calibs.csv            per-take fisheye calibration
#
# Verify availability on the mirror BEFORE running this:
#
#   python3 -c "import json,os; R='/vision/group/egoexo4d/takes'; T=json.load(open('/vision/group/egoexo4d/takes.json')); [print('%-34s cams=%d 448=%d calib=%s' % (t['take_name'], sum(os.path.isfile('%s/%s/frame_aligned_videos/%s.mp4'%(R,t['take_name'],c)) for c in sorted(k for k in (t.get('frame_aligned_videos') or {{}}) if k.startswith('cam'))), len(os.listdir('%s/%s/frame_aligned_videos/downscaled/448'%(R,t['take_name']))) if os.path.isdir('%s/%s/frame_aligned_videos/downscaled/448'%(R,t['take_name'])) else 0, os.path.isfile('%s/%s/trajectory/gopro_calibs.csv'%(R,t['take_name'])))) for t in sorted(T,key=lambda x:x['take_idx']) if t.get('participant_uid')=={pid}]"
#
#   bash scripts/tar_expert{pid}.sh                    # -> <repo>/expert{pid}_takes.tar
#   OUT=/scratch/expert{pid}.tar bash scripts/tar_expert{pid}.sh
#
# The archive is roughly {gb:.1f} GB. Run it detached -- the -v output floods a
# terminal and a Ctrl-C leaves a truncated archive with no resume:
#   nohup bash scripts/tar_expert{pid}.sh > tar{pid}.log 2>&1 &
'''


def body(pid, takes, gb):
    """The runnable half: pre-flight checks, then one tar with literal paths."""
    need_kb = int((gb * 1.25 + 1.0) * 1024 * 1024)
    lines = path_lines(takes)
    args = ' \\\n'.join(lines)
    n_entries = f'{len(takes)} takes x (their cameras + the 448 dir record + its files + calib)'
    return f'''
set -euo pipefail

REPO="$(cd "$(dirname "${{BASH_SOURCE[0]}}")/.." && pwd)"

TAKES_ROOT="${{TAKES_ROOT:-/vision/group/egoexo4d/takes}}"
OUT="${{OUT:-$REPO/expert{pid}_takes.tar}}"

[ -d "$TAKES_ROOT" ] || {{ echo "ERROR: no takes root at $TAKES_ROOT" >&2; exit 1; }}
mkdir -p "$(dirname "$OUT")"

# Checked before a byte is written. Filling a quota mid-tar leaves a truncated
# archive that looks finished, which is a worse failure than refusing to start.
NEED_KB={need_kb}
AVAIL_KB=$(df -Pk "$(dirname "$OUT")" | awk 'NR==2 {{print $4}}')
if [ "$AVAIL_KB" -lt "$NEED_KB" ]; then
    echo "ERROR: need ~$((NEED_KB / 1024 / 1024)) GB at $(dirname "$OUT"), have $((AVAIL_KB / 1024 / 1024)) GB" >&2
    echo "       set OUT to somewhere with room" >&2
    exit 1
fi

cd "$TAKES_ROOT"

# -c create, -h follow symlinks, -v so the log shows every file, -f the
# archive. No -z: the payload is already-encoded H.264.
tar -chvf "$OUT" \\
{args}

echo ""
echo "wrote $OUT  ($(du -h "$OUT" | cut -f1))"
echo "entries: $(tar -tf "$OUT" | wc -l)"
echo ""
echo "expected: {n_entries}"
echo ""
echo "extract on the other side with:"
echo "  tar -xf $(basename "$OUT") -C /their/egoexo4d/takes"
'''


def main():
    """Generate one participant's tar script and report what went into it."""
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('pid', type=int)
    ap.add_argument('--task', default='video')
    ap.add_argument('--note', default='')
    ap.add_argument('--tasks', default=None,
                    help='|-separated task_name filter, for cooking dishes')
    ap.add_argument('--scenario', default=None,
                    help='parent_task_name filter; give this or --tasks, since a '
                         'participant can appear in more than one scenario')
    ap.add_argument('--takes_json', default=None)
    ap.add_argument('--force', action='store_true')
    args = ap.parse_args()

    takes = load_takes(args.takes_json)
    tasks = set(args.tasks.split('|')) if args.tasks else None
    mine = takes_for(takes, args.pid, tasks, args.scenario)
    if not mine:
        raise SystemExit(f'no takes for participant {args.pid}')
    bad = [t['take_name'] for t in mine if not cams_of(t)]
    if bad:
        raise SystemExit(f'takes with no cam* videos (unsupported rig): {bad}')

    gb = estimate_gb(mine)
    out = f'scripts/tar_expert{args.pid}.sh'
    if os.path.exists(out) and not args.force:
        raise SystemExit(f'{out} exists; pass --force to overwrite')
    with open(out, 'w') as f:
        f.write(header(args.pid, mine, args.note, args.task, gb) + body(args.pid, mine, gb))
    os.chmod(out, 0o755)
    print(f'{out}: {len(mine)} takes, {sum(len(cams_of(t)) for t in mine)} 4K videos, '
          f'~{gb:.1f} GB')


if __name__ == '__main__':
    main()
